In [7]:
import numpy as np
unos = np.ones((5,5))
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
ceros = np.zeros((4,4))
ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
aleatorio = np.random.random((2,3))
aleatorio

array([[0.66684818, 0.72875835, 0.36355552],
       [0.43679833, 0.37702016, 0.5754595 ]])

In [17]:
vacia = np.empty((3,2))
print(vacia)

[[0.66684818 0.72875835]
 [0.36355552 0.43679833]
 [0.37702016 0.5754595 ]]


In [18]:
full = np.full((2,2),4)
full

array([[4, 4],
       [4, 4]])

In [19]:
espacio1 = np.arange(0,30,6)
print(espacio1)
espacio2 = np.linspace(0,30,6)
print(espacio2)

[ 0  6 12 18 24]
[ 0.  6. 12. 18. 24. 30.]


In [23]:
identidad = np.identity(5)
identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
matriz = np.array([(1,2,3),(1,4,9)])
print(matriz.ndim)
print(matriz.dtype)
print(matriz.size)

2
int32
6


In [27]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
a = a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [29]:
a[0,1]

9

In [30]:
a.max()

13

In [31]:
a.min()

8

In [32]:
a.sum()

63

In [36]:
np.sqrt(a)

array([[2.82842712, 3.        ],
       [3.16227766, 3.31662479],
       [3.46410162, 3.60555128]])

In [37]:
np.std(a)

1.707825127659933